Repository CS2103-AY1819S1-W16-1/main, pull requests merged in 2018-10, with the labels that each got.

#16 About us
  docs/AboutUs.adoc
Labels: type.Task

#18 Add budget command
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/META-INF/MANIFEST.MF
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/commons/events/ui/CcaPanelSelectionChangedEvent.java
  src/main/java/seedu/address/commons/events/ui/JumpToBudgetRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/ShowBudgetViewEvent.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/BudgetCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/BudgetCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/BudgetBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyBudgetBook.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/VersionedBudgetBook.java
  src/main/java/seedu/address/model/budget/Budget.java
  src/main/java/seedu/address/model/budget/Transaction.java
  src/main/java/seedu/address/model/cca/Cca.java
  src/main/java/seedu/address/model/cca/CommitteeCca.java
  src/main/java/seedu/address/model/cca/CulturalCca.java
  src/main/java/seedu/address/model/cca/SportsCca.java
  src/main/java/seedu/address/model/cca/UniqueCcaList.java
  src/main/java/seedu/address/model/cca/exceptions/CcaNotFoundException.java
  src/main/java/seedu/address/model/cca/exceptions/DuplicateCcaException.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/tag/TagContainsKeywordPredicate.java
  src/main/java/seedu/address/model/tag/UniqueTagList.java
  src/main/java/seedu/address/model/tag/exceptions/DuplicateTagException.java
  src/main/java/seedu/address/model/tag/exceptions/TagNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/BudgetBookStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/XmlAdaptedCca.java
  src/main/java/seedu/address/storage/XmlAdaptedTag.java
  src/main/java/seedu/address/storage/XmlAddressBookStorage.java
  src/main/java/seedu/address/storage/XmlBudgetBookStorage.java
  src/main/java/seedu/address/storage/XmlFileStorage.java
  src/main/java/seedu/address/storage/XmlSerializableBudgetBook.java
  src/main/java/seedu/address/ui/BudgetWindow.java
  src/main/java/seedu/address/ui/CcaCard.java
  src/main/java/seedu/address/ui/CcaListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/BudgetWindow.fxml
  src/main/resources/view/CcaListCard.fxml
  src/main/resources/view/CcaListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/GuiRobot.java
Labels: priority.High, status.Ongoing, type.Story

#20 Updated search command
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SearchCommandParser.java
  src/main/java/seedu/address/model/person/FieldsContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Room.java
  src/main/java/seedu/address/model/person/School.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlAddressBookStorageTest/invalidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/duplicatePersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/invalidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/HelpWindowTest.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/SampleDataTest.java
Labels: priority.High, type.Story

#47 View email on UI
  src/main/java/seedu/address/commons/events/ui/EmailViewEvent.java
  src/main/java/seedu/address/logic/commands/ComposeCommand.java
  src/main/java/seedu/address/logic/parser/ComposeCommandParser.java
  src/main/java/seedu/address/model/EmailModel.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/EmailDirStorage.java
  src/main/java/seedu/address/storage/EmailStorage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ComposeCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/DefaultEmailBuilder.java
Labels: type.Enhancement

#64 Add, Delete Event in Calendar
  src/main/java/seedu/address/commons/events/model/AllDayEventAddedEvent.java
  src/main/java/seedu/address/commons/events/model/CalendarEventAddedEvent.java
  src/main/java/seedu/address/commons/events/model/CalendarEventDeletedEvent.java
  src/main/java/seedu/address/logic/commands/AddAllDayEventCommand.java
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/parser/AddAllDayEventCommandParser.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteEventCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/CalendarModel.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/CalendarStorage.java
  src/main/java/seedu/address/storage/IcsCalendarStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/resources/ical4j.properties
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, type.Story

#71 Developer Guide (Email)
  docs/DeveloperGuide.adoc
  docs/images/gilgameshtc.png
  docs/images/kengwoon.jpeg
  docs/images/kengwoon.png
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/storage/EmailStorage.java
Labels: priority.High, type.Task

#73 Developer Guide (Calendar)
  docs/DeveloperGuide.adoc
Labels: priority.High, type.Task

#43 Import XML files
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/EraseCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EraseCommandParser.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/data/ImportCommandTest/ccaImports.xml
  src/test/data/ImportCommandTest/contactImports.xml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EraseCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
Labels: priority.High, type.Story

#112 Export command
  build.gradle
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/events/model/ExportAddressBookEvent.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/commands/imports/ImportAddressBook.java
  src/main/java/seedu/address/logic/commands/imports/ImportCcaList.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ClearCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/CalendarModel.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/ContactContainsTagPredicate.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/XmlAddressBookStorage.java
  src/test/data/ImportCommandTest/ccaImports.xml
  src/test/data/ImportCommandTest/invalidFormat.xml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/logic/parser/ClearCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ImportCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/ContactContainsRoomPredicateTest.java
  src/test/java/seedu/address/model/person/ContactContainsTagPredicateTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
Labels: priority.High, type.Enhancement

#98 Enhance Email feature
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/ccabook.xsl
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/events/model/EmailLoadedEvent.java
  src/main/java/seedu/address/commons/events/storage/EmailDeleteEvent.java
  src/main/java/seedu/address/commons/events/storage/EmailLoadEvent.java
  src/main/java/seedu/address/commons/events/ui/EmailNotFoundEvent.java
  src/main/java/seedu/address/commons/events/ui/ListEmailsEvent.java
  src/main/java/seedu/address/logic/commands/ComposeCommand.java
  src/main/java/seedu/address/logic/commands/ComposeEmailIndexCommand.java
  src/main/java/seedu/address/logic/commands/ComposeEmailListCommand.java
  src/main/java/seedu/address/logic/commands/DeleteEmailCommand.java
  src/main/java/seedu/address/logic/commands/ListEmailsCommand.java
  src/main/java/seedu/address/logic/commands/ViewEmailCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ComposeEmailIndexCommandParser.java
  src/main/java/seedu/address/logic/parser/ComposeEmailListCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteEmailCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ViewEmailCommandParser.java
  src/main/java/seedu/address/model/EmailModel.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/EmailDirStorage.java
  src/main/java/seedu/address/storage/EmailStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ComposeCommandTest.java
  src/test/java/seedu/address/logic/commands/ComposeEmailIndexCommandTest.java
  src/test/java/seedu/address/logic/commands/ComposeEmailListCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteEmailCommandTest.java
  src/test/java/seedu/address/logic/commands/EraseCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewEmailCommandTest.java
  src/test/java/seedu/address/logic/parser/ComposeEmailListCommandParserTest.java
  src/test/java/seedu/address/testutil/DefaultEmailBuilder.java
  src/test/java/seedu/address/testutil/TypicalEmails.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.High, type.Enhancement

#120 Update Calendar Feature in UGDG
  docs/UserGuide.adoc
  docs/images/add_all_day_event_diagram_after.png
  docs/images/add_all_day_event_diagram_before.png
  docs/images/add_event_diagram_after.png
  docs/images/add_event_diagram_before.png
  docs/images/calendar_view_diagram.png
  docs/images/delete_event_diagram_after_invalid.png
  docs/images/delete_event_diagram_after_valid.png
  docs/images/delete_event_diagram_before.png
Labels: priority.High, status.Ongoing, type.Task
