Repository CS2103-AY1819S1-W16-1/main, pull requests merged in 2018-09, with the labels that each got.

#2 Added most user stories and use cases
  docs/DeveloperGuide.adoc
Labels: status.Ongoing

#1 About us
  docs/AboutUs.adoc
  docs/images/damithc.jpg
  docs/images/eatorbeeaten.jpeg
  docs/images/ericyjw.JPG
  docs/images/lejolly.jpg
  docs/images/m133225.jpg
  docs/images/yijinl.jpg
  docs/images/yl_coder.jpg
  docs/team/eatorbeeaten.adoc
  docs/team/ericyjw.adoc
  docs/team/gilgameshtc.adoc
  docs/team/javenseow.adoc
  docs/team/kengwoon.adoc
  docs/team/team.adoc
Labels: status.Ongoing

#17 Create calendar feature
  .gitignore
  build.gradle
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/events/model/CalendarCreatedEvent.java
  src/main/java/seedu/address/logic/commands/CreateCalendarCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CreateCalendarCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/CalendarModel.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/calendar/Month.java
  src/main/java/seedu/address/model/calendar/Year.java
  src/main/java/seedu/address/storage/CalendarStorage.java
  src/main/java/seedu/address/storage/IcsCalendarStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.High, status.Ongoing, type.Story

#13 Compose email feature
  .gitignore
  build.gradle
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/events/model/EmailSavedEvent.java
  src/main/java/seedu/address/logic/commands/ComposeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ComposeCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/EmailModel.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/email/Content.java
  src/main/java/seedu/address/model/email/Subject.java
  src/main/java/seedu/address/storage/EmailDirStorage.java
  src/main/java/seedu/address/storage/EmailStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.High, type.Story
