Repository CS2103-AY1819S1-W16-1/main, pull requests merged in 2018-11, with the labels that each got.

#164 Resolve Calendar UI on Mac OS bug
  .gitignore
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/ui/CalendarPanel.java
Labels: severity.Medium, type.Bug

#134 add more Import types
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/ccabook.xsl
  docs/diagrams/ClearCommandActivityDiagram.pptx
  docs/diagrams/ClearCommandSequenceDiagram.pptx
  docs/diagrams/EraseCommandActivityDiagram.pptx
  docs/diagrams/EraseCommandSequenceDiagram.pptx
  docs/diagrams/ExportCommandActivityDiagram.pptx
  docs/diagrams/ExportCommandSequenceDiagram.pptx
  docs/diagrams/ImportCommandActivityDiagram.pptx
  docs/diagrams/ImportCommandSequenceDiagram.pptx
  docs/images/BudgetBookExample.png
  docs/images/ClearCommandActivityDiagram.png
  docs/images/ClearCommandSequenceDiagram.png
  docs/images/EraseCommandActivityDiagram.png
  docs/images/EraseCommandSequenceDiagram.png
  docs/images/ExportCommandActivityDiagram.png
  docs/images/ExportCommandSequenceDiagram.png
  docs/images/ImportCommandActivityDiagram.png
  docs/images/ImportCommandSequenceDiagram.png
  docs/images/TransactionsExample.png
  docs/team/kengwoon.adoc
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/EraseCommand.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/commands/imports/ImportAddressBook.java
  src/main/java/seedu/address/logic/commands/imports/ImportBudgetBook.java
  src/main/java/seedu/address/logic/commands/imports/ImportCcaList.java
  src/main/java/seedu/address/logic/commands/imports/ImportTransaction.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/BudgetBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/cca/UniqueCcaList.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/data/ImportCommandTest/budgetBookImports.xml
  src/test/data/ImportCommandTest/transactionImports.xml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/EraseCommandSystemTest.java
Labels: priority.Medium, type.Enhancement

#166 Updated documentation and created test cases
  calendar/AUG-2018.ics
  calendar/SEP-2018.ics
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Image Sequence Diagram.png
  docs/images/SearchExample.png
  docs/images/SearchExample2.png
  docs/images/SearchExampleAfter.png
  docs/images/Ui.png
  docs/images/desktop.ini
  docs/team/javenseow.adoc
  src/main/java/seedu/address/logic/commands/ImageCommand.java
  src/main/java/seedu/address/logic/parser/ImageCommandParser.java
  src/main/java/seedu/address/model/person/ProfilePicture.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/resources/ProfileWindow.html
  src/main/resources/profile_picture/a123.jpg
  src/test/data/ImageCommandTest/Invalid.png
  src/test/data/ImageCommandTest/Valid.jpg
  src/test/java/guitests/guihandles/BrowserPanelHandle.java
  src/test/java/guitests/guihandles/ProfileViewUtil.java
  src/test/java/seedu/address/logic/commands/ImageCommandTest.java
  src/test/java/seedu/address/logic/parser/ImageCommandParserTest.java
  src/test/java/seedu/address/model/person/ProfilePictureTest.java
  src/test/java/seedu/address/storage/ProfilePictureDirStorageTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SearchCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.High, type.Task

#160 Tests and documentation for Email features
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/compose_email_index.png
  docs/images/compose_email_list.png
  docs/images/list.png
  docs/images/view_email.png
  src/main/java/seedu/address/logic/commands/ComposeEmailIndexCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/EmailModel.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/email/Content.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateCcaCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteEmailCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewEmailCommandParserTest.java
  src/test/java/seedu/address/model/EmailModelTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/EmailDirStorageTest.java
  src/test/java/seedu/address/testutil/EmailUtil.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/DeleteEmailCommandSystemTest.java
Labels: priority.High

#174 Updated Calendar Feature DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/CalendarCommandActivityDiagram.pptx
  docs/diagrams/CalendarCommandSequenceDiagram.pptx
  docs/images/AddAllDayEventSeqDiagram.png
  docs/images/AddEventSeqDiagram.png
  docs/images/CalendarCommandActivityDiagram.png
  docs/images/CreateCalendarSeqDiagram.png
  docs/images/DeleteEventSeqDiagram.png
  docs/images/ViewCalendarSeqDiagram.png
  docs/team/gilgameshtc.adoc
Labels: priority.Medium, type.Task
